### ISSUE TITLE
removeBrackets breaks content

### ISSUE THREAD

**Issue by pdf** [PiotrKowalski/html-to-gomponents#8]
The call to `removeBrackets()` here:

https://github.com/PiotrKowalski/html-to-gomponents/blob/2f23f77782c15a601793242389e96c8f25d00aad/internal/domain/node.go#L95

Breaks content such as class names containing legitimate brackets.

Can you describe what problem this function is attempting to solve?

**Comment by PiotrKowalski** [comment]
Ye. I put this function at the beggining of this project to solve specific issue. I wanted to remove brackets because when I switched array to string it would return the string with brackets.
It was a temporary solution, give me sec. WIll check if it can be removed. I will use split function or sth similar probably then

**Comment by PiotrKowalski** [comment]
#9 will fix it when merged
